import { AssetDefinition } from "@/store/assetStore";

export const DEFAULT_ASSET_LIBRARY: AssetDefinition[] = [
  {
    id: "char-judge",
    name: "Judge",
    category: "characters",
    thumbnailUrl: "/assets/thumbnails/judge.png",
    modelUrl: "/assets/models/characters/judge.glb",
    defaultRole: "judge",
    tags: ["character", "judge"],
  },
  {
    id: "char-prosecutor",
    name: "Prosecutor",
    category: "characters",
    thumbnailUrl: "/assets/thumbnails/prosecutor.png",
    modelUrl: "/assets/models/characters/prosecutor.glb",
    defaultRole: "prosecutor",
    tags: ["character", "prosecutor"],
  },
  {
    id: "char-defense",
    name: "Defense Lawyer",
    category: "characters",
    thumbnailUrl: "/assets/thumbnails/defense.png",
    modelUrl: "/assets/models/characters/defense.glb",
    defaultRole: "defense",
    tags: ["character", "defense"],
  },
  {
    id: "char-witness",
    name: "Witness",
    category: "characters",
    thumbnailUrl: "/assets/thumbnails/witness.png",
    modelUrl: "/assets/models/characters/witness.glb",
    defaultRole: "witness",
    tags: ["character", "witness"],
  },
  {
    id: "char-police",
    name: "Police Officer",
    category: "characters",
    thumbnailUrl: "/assets/thumbnails/police.png",
    modelUrl: "/assets/models/characters/police.glb",
    defaultRole: "police",
    tags: ["character", "police"],
  },
  {
    id: "char-audience",
    name: "Audience Member",
    category: "characters",
    thumbnailUrl: "/assets/thumbnails/audience.png",
    modelUrl: "/assets/models/characters/audience.glb",
    defaultRole: "audience",
    tags: ["character", "audience"],
  },
  {
    id: "prop-bench",
    name: "Court Bench",
    category: "furniture",
    thumbnailUrl: "/assets/thumbnails/bench.png",
    modelUrl: "/assets/models/props/bench.glb",
    tags: ["furniture", "bench"],
  },
  {
    id: "prop-table",
    name: "Table",
    category: "furniture",
    thumbnailUrl: "/assets/thumbnails/table.png",
    modelUrl: "/assets/models/props/table.glb",
    tags: ["furniture", "table"],
  },
  {
    id: "tech-screen",
    name: "Evidence Screen",
    category: "tech",
    thumbnailUrl: "/assets/thumbnails/screen.png",
    modelUrl: "/assets/models/tech/evidence_screen.glb",
    tags: ["tech", "screen", "evidence"],
  },
  {
    id: "tech-monitor",
    name: "Monitor",
    category: "tech",
    thumbnailUrl: "/assets/thumbnails/monitor.png",
    modelUrl: "/assets/models/tech/monitor.glb",
    tags: ["tech", "monitor"],
  },
  {
    id: "tech-microphone",
    name: "Microphone",
    category: "tech",
    thumbnailUrl: "/assets/thumbnails/mic.png",
    modelUrl: "/assets/models/tech/microphone.glb",
    tags: ["tech", "microphone"],
  },
  {
    id: "tech-camera",
    name: "Camera Rig",
    category: "cameras",
    thumbnailUrl: "/assets/thumbnails/camera.png",
    modelUrl: "/assets/models/tech/camera.glb",
    tags: ["camera"],
  },
];
